### ISSUE TITLE
Is it really correctly implemented?

### ISSUE THREAD

**Issue by fgfuchs** [ThunderStruct/Color-Utilities#1]
Hi, 
I am trying to use this repo, but the following gives:
    ColorUtils::rgbColor color(0.0f, 0.0f, 0.0f);
    ColorUtils::rgbColor color_ref(1.0f, 0.0f, 0.0f);
    float deltaE = ColorUtils::getColorDeltaE(color, color_ref);
    std::cout<<"deltaE="<<deltaE<<std::endl;
**deltaE=117.345**
However the following python script gives:
import skimage.color as skco
rlab=skco.rgb2lab(np.array([[[0.0,0.0,0.0]]]))
dlab=skco.rgb2lab(np.array([[[1.0,0.0,0.0]]]))
skco.deltaE_ciede2000(rlab,dlab)
**50.41122852**
and also http://colormine.org/delta-e-calculator/cie2000
gives: **50.4067**

Am I using the code in the wrong way, or is it incorrectly implemented (it gives a different result consistently).

**Comment by ThunderStruct** [comment]
Hi Franz!
The calculator is correctly implemented. The scikit snippet and the link you provided simply use a different algorithm that corrects for lightness (CIE2000) while the algorithm used for this library (CIE76/94) doesn't.
You may validate your results using [this](http://colormine.org/delta-e-calculator) or [this](http://colormine.org/delta-e-calculator/cie94) calculator instead.
This colorwiki [link](http://www.colorwiki.com/wiki/Delta_E:_The_Color_Difference#dE94) might also be helpful!

I'll add the algorithm used in the README so it's clearer for everyone and will try to add an option for dE2000 in the future. 

Good luck!

**Comment by fgfuchs** [comment]
Thank you for your answer.

**Comment by ThunderStruct** [comment]
My pleasure! :-)
